Added WP CLI command for flushing caches.
acato-plugins/wp-rest-cache pull request #5
Opened 2021-02-11 15:01 UTC by richardkorthuis

2021-02-11 15:02 UTC, acato-plugins requested changes
**phpcs** scanning turned up:

:no_entry_sign: 2 errors 

***

**hashes-api**-scanning skipped

2021-02-11 15:02 UTC, acato-plugins commented on includes/cli/class-flush-command.php
> +<?php
:no_entry_sign: **Error**: Class file names should be based on the class name with &quot;class-&quot; prepended. Expected class-flush-command.php, but found phpcs-scan-3yuYoP.php (*WordPress.Files.FileName.InvalidClassFileName*).

2021-02-11 15:02 UTC, acato-plugins commented on includes/cli/class-flush-command.php
> +<?php
:no_entry_sign: **Error**: Filenames should be all lowercase with hyphens as word separators. Expected phpcs-scan-3yuyop.php, but found phpcs-scan-3yuYoP.php (*WordPress.Files.FileName.NotHyphenatedLowercase*).

2021-02-11 15:02 UTC, acato-plugins commented
GitHub API communication error. Please contact a human. (commit-ID: 567f4c424018f780868e46de1bc28e78983b15f4).

2021-02-13 13:53 UTC, yoeridekker approved these changes
Nice!

2021-02-24 13:49 UTC, merged